"use client";

import { useEffect } from "react";
import { getCalApi } from "@calcom/embed-react";
import {
  CAL_NAMESPACES,
  CAL_SERVICES,
  CAL_TRIGGER_CONFIG,
  CARD_HOLD_NOTICE,
  basePrice,
  calLink,
} from "@/lib/config/cal-events";
import { formatPrice } from "@/lib/config/business-rules";
import { CAL_UI_CONFIG } from "@/lib/cal/embed-ui";

/** Matches the origin in the embed snippets generated by Cal.com. */
const CAL_ORIGIN = "https://app.cal.com";

/**
 * Service menu that opens the Cal.com booking popup on click.
 *
 * Cal's embed script attaches a global click listener for `[data-cal-link]`
 * elements, so the triggers below need no click handlers of their own. Each
 * event type gets its own namespace, themed once on mount.
 *
 * Triggers are buttons rather than links on purpose: Cal's handler does not
 * call `preventDefault()`, so an anchor would navigate away while the modal
 * opens.
 */
export default function CalBookingMenu() {
  useEffect(() => {
    let active = true;

    (async () => {
      for (const namespace of CAL_NAMESPACES) {
        const cal = await getCalApi({ namespace });
        if (!active) return;

        // forwardQueryParams is deliberately left off. It copies the visiting
        // page's query string into the booker, so an ad or campaign link
        // (?fbclid=, ?utm_=) hands Cal params it then has to parse — a
        // plausible source of the crash reported in its booker.
        cal("ui", CAL_UI_CONFIG);
      }
    })();

    return () => {
      active = false;
    };
  }, []);

  return (
    <div className="mx-auto max-w-5xl">
      <div className="grid gap-6 md:grid-cols-2">
        {CAL_SERVICES.map((service, i) => (
          <article
            key={service.id}
            className={`luxury-card animate-fade-up group flex flex-col p-8 ${
              service.featured ? "signature-card" : ""
            }`}
            style={{ animationDelay: `${i * 0.1}s` }}
          >
            <p className="font-display mb-3 text-[11px] tracking-[0.3em] text-gold/70">
              {service.eyebrow}
            </p>
            <div className="mb-3 flex items-baseline justify-between gap-4">
              <h2 className="text-xl font-semibold tracking-wide transition-colors duration-300 group-hover:text-gold">
                {service.name}
              </h2>
              <p className="shrink-0 text-right">
                {service.durations.length > 1 && (
                  <span className="mr-1.5 text-[10px] tracking-[0.2em] text-muted/60">
                    FROM
                  </span>
                )}
                <span className="text-gold-gradient text-xl font-bold">
                  {formatPrice(basePrice(service))}
                </span>
              </p>
            </div>
            <p className="mb-8 flex-1 text-sm leading-relaxed text-muted">
              {service.description}
            </p>

            <div className="flex flex-wrap items-center gap-3">
              {service.durations.map((duration) => (
                <button
                  key={duration.slug}
                  type="button"
                  data-cal-link={calLink(duration.slug)}
                  data-cal-namespace={duration.namespace}
                  data-cal-origin={CAL_ORIGIN}
                  data-cal-config={CAL_TRIGGER_CONFIG}
                  aria-label={`Book ${service.name}, ${duration.minutes} minutes, ${formatPrice(duration.price)}`}
                  className="btn-glow group/btn relative cursor-pointer border border-gold/40 px-6 py-3 text-center transition-all duration-300 hover:border-gold hover:bg-gold hover:shadow-[0_0_16px_rgba(187,145,89,0.2)]"
                >
                  <span className="block text-xs font-semibold tracking-widest text-gold transition-colors duration-300 group-hover/btn:text-background">
                    {duration.minutes} MIN
                  </span>
                  <span className="mt-1 block text-sm font-bold text-foreground transition-colors duration-300 group-hover/btn:text-background">
                    {formatPrice(duration.price)}
                  </span>
                </button>
              ))}
            </div>
          </article>
        ))}
      </div>

      <p className="animate-fade-up mx-auto mt-10 max-w-2xl border-l-2 border-gold/20 py-1 pl-5 text-sm leading-relaxed text-muted">
        {CARD_HOLD_NOTICE}
      </p>
    </div>
  );
}
