"use client";

import { useEffect } from "react";
import { getCalApi } from "@calcom/embed-react";
import {
  CAL_NAMESPACES,
  CAL_SERVICES,
  CAL_TRIGGER_CONFIG,
  calLink,
} from "@/lib/config/cal-events";
import { CAL_UI_CONFIG } from "@/lib/cal/embed-ui";

/** Matches the origin in the embed snippets generated by Cal.com. */
const CAL_ORIGIN = "https://app.cal.com";

/**
 * Service menu that opens the Cal.com booking popup on click.
 *
 * Cal's embed script attaches a global click listener for `[data-cal-link]`
 * elements, so the triggers below need no click handlers of their own. Each
 * event type gets its own namespace, themed once on mount.
 *
 * Triggers are buttons rather than links on purpose: Cal's handler does not
 * call `preventDefault()`, so an anchor would navigate away while the modal
 * opens.
 */
export default function CalBookingMenu() {
  useEffect(() => {
    let active = true;

    (async () => {
      for (const namespace of CAL_NAMESPACES) {
        const cal = await getCalApi({ namespace });
        if (!active) return;

        // Carries UTM and prefill params (?name=, ?email=) into the booking.
        cal.config = { ...cal.config, forwardQueryParams: true };
        cal("ui", CAL_UI_CONFIG);
      }
    })();

    return () => {
      active = false;
    };
  }, []);

  return (
    <div className="mx-auto max-w-5xl">
      <div className="grid gap-6 md:grid-cols-2">
        {CAL_SERVICES.map((service, i) => (
          <article
            key={service.id}
            className="luxury-card animate-fade-up group flex flex-col p-8"
            style={{ animationDelay: `${i * 0.1}s` }}
          >
            <p className="mb-3 text-[11px] tracking-[0.3em] text-gold/70">
              {service.eyebrow}
            </p>
            <h2 className="mb-3 text-xl font-semibold tracking-wide transition-colors duration-300 group-hover:text-gold">
              {service.name}
            </h2>
            <p className="mb-8 flex-1 text-sm leading-relaxed text-muted">
              {service.description}
            </p>

            <div className="flex flex-wrap items-center gap-3">
              {service.durations.map((duration) => (
                <button
                  key={duration.slug}
                  type="button"
                  data-cal-link={calLink(duration.slug)}
                  data-cal-namespace={duration.namespace}
                  data-cal-origin={CAL_ORIGIN}
                  data-cal-config={CAL_TRIGGER_CONFIG}
                  aria-label={`Book ${service.name}, ${duration.minutes} minutes`}
                  className="btn-glow relative cursor-pointer border border-gold/40 px-6 py-3 text-xs font-semibold tracking-widest text-gold transition-all duration-300 hover:border-gold hover:bg-gold hover:text-background hover:shadow-[0_0_16px_rgba(201,168,76,0.2)]"
                >
                  {duration.minutes} MIN
                </button>
              ))}
            </div>
          </article>
        ))}
      </div>
    </div>
  );
}
