import {
  CAL_TRIGGER_CONFIG,
  calLink,
  type CalDuration,
} from "@/lib/config/cal-events";
import { formatPrice } from "@/lib/config/business-rules";

/** Matches the origin in the embed snippets generated by Cal.com. */
const CAL_ORIGIN = "https://app.cal.com";

/**
 * One length-and-price button that opens the Cal.com booker. A button rather
 * than a link on purpose: Cal's click handler does not call
 * `preventDefault()`, so an anchor would navigate away while the modal opens.
 */
export default function CalDurationButton({
  serviceName,
  duration,
}: {
  serviceName: string;
  duration: CalDuration;
}) {
  return (
    <button
      type="button"
      data-cal-link={calLink(duration.slug)}
      data-cal-namespace={duration.namespace}
      data-cal-origin={CAL_ORIGIN}
      data-cal-config={CAL_TRIGGER_CONFIG}
      aria-label={`Book ${serviceName}, ${duration.minutes} minutes, ${formatPrice(duration.price)}`}
      className="btn-glow group/btn relative cursor-pointer border border-gold/40 px-6 py-3 text-center transition-all duration-300 hover:border-gold hover:bg-gold hover:shadow-[0_0_16px_rgba(187,145,89,0.2)]"
    >
      <span className="block text-xs font-semibold tracking-widest text-gold transition-colors duration-300 group-hover/btn:text-background">
        {duration.minutes} MIN
      </span>
      <span className="mt-1 block text-sm font-bold text-foreground transition-colors duration-300 group-hover/btn:text-background">
        {formatPrice(duration.price)}
      </span>
    </button>
  );
}
